# Generated by Django 5.2.3 on 2025-07-02 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prompt', models.TextField()),
                ('models_compared', models.JSONField(default=list)),
                ('results', models.JSONField(default=dict)),
                ('winner', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TensorZeroInference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_name', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('inference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('function_name', models.CharField(default='chat', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TensorZeroFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('inference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tensorzero_showcase.tensorzeroinference')),
            ],
        ),
    ]
